# Generated by Django 3.0.3 on 2020-03-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0011_newsemail_joined_date'),
        ('users', '0002_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookshelf',
            field=models.ManyToManyField(to='pdf.Book'),
        ),
    ]
