# Generated by Django 3.0.3 on 2020-03-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_book_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
