# Generated by Django 3.0.3 on 2020-03-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_book_suggest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
