# Generated by Django 3.0.3 on 2020-03-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_auto_20200308_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ImageField(blank=True, max_length=600, null=True, upload_to=''),
        ),
    ]
