# Generated by Django 3.0.3 on 2020-03-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0006_book_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
