# Generated by Django 3.0.3 on 2020-03-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0008_auto_20200308_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
