# Generated by Django 3.0.3 on 2020-03-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0009_newsemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsemail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
